version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - '5675:5672'
      - '15675:15672'
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=synch
      - RABBITMQ_DEFAULT_PASS=synch

volumes:
  postgres_data:
