@startuml


OrdersInstaleapMock --> Tessy: Receive the event

Tessy --> WoltMock: Get order details
WoltMock --> Tessy: Order details

Tessy --> Tessy: Build replace items payload
Tessy --> WoltMock: Replace items in order

WoltMock --> Tessy: Accepted
@enduml